lab_login/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

# Create your urls here
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^post_status', post_status, name='post-status'),
    url(r'^get-user-list/$', get_user_list, name='get-user-list'),
    url(r'^update_profile/$', update_profile, name='update_profile'),
    
]

lab_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, update_data

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit_profile/$', edit_profile, name='edit_profile'),
    url(r'^update_data/$', update_data, name='update_data'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
import lab_search.urls as lab_search
import lab_profile.urls as lab_profile
import lab_login.urls as lab_login
import lab_history.urls as lab_history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/', include(lab_search, namespace='lab-search')),
    url(r'^lab-profile/', include(lab_profile, namespace='lab-profile')),
    url(r'^lab-login/', include(lab_login, namespace='lab-login')),
	url(r'^lab-history/', include(lab_login, namespace='lab-history')),
    url(r'^$', RedirectView.as_view(url = 'lab-login/', permanent=True), name='index'),
]

lab_login/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

# Create your models here
#class Skill(models.Model):
#    SKILL_TYPES = (
#        ('J', 'Java'),
#        ('Py', 'Python'),
#        ('C', 'C'),
#        ('C+', 'C++'),
#        ('P', 'PHP'),
#        ('E', 'English')
#        )
#    SKILL_LEVEL = [
#        ('N', 'Noob'),
#        ('B', 'Beginner'),
#        ('I', 'Intermediate'),
#        ('A', 'Advance'),
#        ('E', 'Expert'),
#        ('L', 'Legend'),
#        ('V', 'Vinny')
#        ]
#    skillType = models.CharField(max_length=20, choices=SKILL_TYPES)
#    skillLevel = models.CharField(max_length=20, choices=SKILL_LEVEL)
    
class User(models.Model):
    identity_number = models.CharField(max_length=20)
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200, default="")
    linkedin = models.CharField(max_length=200, default="")
    angkatan = models.CharField(max_length=20)
    picture_link = models.CharField(max_length=200, default="")
#    skills = models.ManyToManyField(Skill)
    skills = models.CharField(max_length=500, default="")
    def __str__(self):  # __unicode__ on Python 2
        return self.name

class Status(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

lab_login/forms.py
from django import forms

# Create your forms here
class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please fill this input',
    }
    
    status_attrs = {
        'type': 'text',
				
        'class': 'status-form-textarea',
        'placeholder':'What is on your mind?...'
    }
    
    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

lab_login/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.core import serializers
from .forms import Status_Form
from .models import User, Status
import json

# Create your views here
response = {}
flag = 0
response["author"] = "ParaPengabdiBeskem"
def index(request): 
    if 'user_login' in request.session:
        global flag
        if(flag == 1):
            flag = 0
        return HttpResponseRedirect(reverse('lab-login:dashboard'))
    else:
        html = 'lab_login/login.html'
        return render(request, html, response)
    
def dashboard(request): 
    if 'user_login' in request.session:
        response['is_login'] = True

        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username, angkatan="20"+kode_identitas[0:2])
        my_Status= Status.objects.filter(user_id=response['user'].id)
        response['all_status'] = Status.objects.filter(user_id=response['user'].id)
        response['Status']= response['all_status'][::-1]

        if len(my_Status)== 0:
            response['last_status']='-'
        else:
            response['last_Status']=response['Status'][0]

        response['status_count'] = response['all_status'].count()
        response['status_form'] = Status_Form

        set_data_for_session(response,request)
        html = 'lab_login/dashboard.html'
        return render(request, html, response)
    
    response['is_login'] = False
    html = 'lab_login/login.html'
    return render(request, html, response)

def set_data_for_session(res, request):
    global flag
    if(flag == 0):
        #=========[FOR PROFILE]=========#
        request.session['nama'] = 'kosong'
        request.session['keahlian'] = 'kosong'
        request.session['email'] = 'kosong'
        request.session['linkedin'] = 'kosong'
        request.session['gambar'] = "https://d30y9cdsu7xlg0.cloudfront.net/png/363633-200.png"
        #===============================#
        flag = 1

    response['nama'] = request.session['nama']
    response['keahlian'] = request.session['keahlian']
    response['email'] = request.session['email']
    response['linkedin'] = request.session['linkedin']
    response['gambar'] = request.session['gambar']

    response['author'] = request.session['user_login']
    response['access_token'] = request.session['access_token']
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

def post_status(request): 
    form = Status_Form(request.POST or None)
    if 'user_login' in request.session and request.method == 'POST' and form.is_valid():
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        status_message = request.POST['status']
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username, angkatan="20"+kode_identitas[0:2])
        new_status = Status.objects.create(description=status_message, user=response['user'])
        return HttpResponseRedirect(reverse('lab-login:dashboard'))
        
    response['is_login'] = False
    html = 'lab_login/login.html'
    return render(request, html, response)

def get_user_list(request):
    if request.method == 'GET':
        user_list = User.objects.all()
        data = serializers.serialize('json', user_list)
        return HttpResponse(data)

def update_profile(request):
    if request.method == 'POST':
        npm = request.session["kode_identitas"]
        user = User.objects.get(identity_number = npm)
        data = json.loads(list(request.POST.keys())[list(request.POST.values()).index('')])

        user.name = data['name']
        user.email = data['email']
        user.linkedin = data['linkedin']
        user.picture_link = data['picture']
        user.skills = data['skills']

        request.session['nama'] = user.name
        request.session['email'] = user.email
        request.session['linkedin'] = user.linkedin
        request.session['gambar'] = user.picture_link
        request.session['keahlian'] = user.skills

        print(data)
        print(data['skills'])
        
        user.save()         # ERROR
        user_list = User.objects.all()
        a = serializers.serialize('json', user_list)
        print(a)

    return JsonResponse({"success":"true"})

lab_login/templates/lab_login/dashboard.html
{% extends "lab_login/layout/base2.html" %}
{% load staticfiles %}
{% load static %}
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/lab_login.css' %}" />
</head>

{% block content %}
<!-- Content Here -->
<div class="pojok-kanan">
</div>
<br>
<div class="panel panel-default">
    <div class="panel-heading" style="background-color:#3db4d8">
        <b><p class="head" > Welcome Basecamp Devotee, {{ user.name }} </h2></p>
    </div>
    <div class="panel-body" style="background-color: lightgray;">
		<img src={{ gambar }} class="img-circle" height="150" width="150" align="left"></img>
        <b style="text-align:left"><img src="https://png.icons8.com/metro/540/new-post.png" width="35px" height="35px" id="img-forum"></img> {{ status_count }}</b><br>
		<h4 style="text-align:center;float:up;" class="last-status"><br> <p style="text-align:center"><i><b> " {{last_Status.description}}"</b></p></i></h4>

    </div>
    <div class="panel-footer">
        <a href="{% url 'lab-profile:edit_profile' %}" class="btn btn-info"> Edit Profile </a>
    </div>

</div>

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist" >
        <li role="presentation" class="active">
            <a href="#status" aria-controls="home" role="tab" data-toggle="tab"> Status </a>
        </li>
	   <li role="presentation">
            <a href="#profile" aria-controls="settings" role="tab" data-toggle="tab"> Profile</a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>


    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="status">
            {% include 'lab_login/tabs/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="profile">
            <!-- Apply the same here -->
            {% include 'lab_profile/pages/profile.html' %}

        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            <!-- Apply the same here -->

        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            <!-- Apply the same here -->
            {% include 'lab_search/lab_search.html' %}
        </div>
    </div>
</div>
{% endblock %}

lab_login/templates/lab_login/login.html
{% extends "lab_login/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <img src="https://basecampclimbing.ca/static/basecamp/img/logo.png" width="150px" height="150px" class="gambarku">
            </div>
            <form action="{% url 'lab-login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
					<label for="username"> Password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary" value="Login" id="login-but">
            </form>
        </div>
    </div>
</div>
{% endblock %}