lab_login/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

# Create your urls here
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^post_status', post_status, name='post-status'),
    url(r'^get-user-list/$', get_user_list, name='get-user-list'),
    url(r'^update_profile/$', update_profile, name='update_profile'),
    
]

lab_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, update_data

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit_profile/$', edit_profile, name='edit_profile'),
    url(r'^update_data/$', update_data, name='update_data'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
import lab_search.urls as lab_search
import lab_profile.urls as lab_profile
import lab_login.urls as lab_login
import lab_history.urls as lab_history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/', include(lab_search, namespace='lab-search')),
    url(r'^lab-profile/', include(lab_profile, namespace='lab-profile')),
    url(r'^lab-login/', include(lab_login, namespace='lab-login')),
	url(r'^lab-history/', include(lab_login, namespace='lab-history')),
    url(r'^$', RedirectView.as_view(url = 'lab-login/', permanent=True), name='index'),
]

lab_profile/models.py
from django.db import models

# Create your models here.

lab_profile/views.py
from django.shortcuts import render
from lab_login.models import User
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from lab_login.views import update_profile
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.

response = {}
def index(request):
    html = 'lab_profile/pages/profile.html'
    response['author'] = 'Para Pengabdi Beskem'
    return render(request, html, response)

#========================================================================

def edit_profile(request):
    html = 'lab_profile/edit_profile.html'
    response = get_datas(request)
    return render(request, html, response)

def get_datas(request):
    npm = request.session['kode_identitas']
    user = User.objects.filter(identity_number=npm)
    data = json.loads(serializers.serialize('json', user))
    return data[0]

@csrf_exempt
def update_data(request):
    return HttpResponse(update_profile(request))

lab_profile/templates/lab_profile/edit_profile.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<script type="text/javascript" src="//platform.linkedin.com/in.js">
    	api_key:   81g8jij0ht1lyp
    	authorize: true
    	lang:      en_US
    	onLoad:    onLinkedInLoad
	</script>
</head>
<body>
	<content>
		{% csrf_token %}
		<div>
			<script type="in/Login" class="login"></script>
			<div id="get-data"></div>
		</div>

		<div>
			<p> NPM : {{ fields.identity_number }} </p>
		</div>

		<div>
			<button onclick="updateData();" class="finished">Submit</button>
			<button onclick="window.location = '/lab-login/dashboard/';" class="exit">Exit</button>
		</div>

		<div class="select2-container">
			<h3>Skills</h3>
			<div class="select2" id="0">
				<select class="my-select-1"></select>
				<select class="my-select-2"></select>
				<button class="remove-my-select" onclick="remove('#0')"> - </button>
			</div>
		</div>

		<div>
			<button id="add-my-select">Add More Skills</button>
			<div class="radio-btn" id="show-score">
				<h3>Show Scores?</h3>
				<form action="">
  					<input type="radio" class="true-show" name="score" value="yes" checked> Yes
  					<input type="radio" class="false-show" name="score" value="no"> No
				</form>
			</div>
		</div>
	</content>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://code.jquery.com/qunit/qunit-2.4.1.js"></script>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
</body>
</html>
<script>

	var name, email, linkedin, picture;

	$(document).ready(function(){
		//---INPUT CODE HERE---//
		// Starts when the page is fully loaded (without any error)

		var skill = [
					{"id":0,"text":"Java"},
					{"id":1,"text":"Python"},
					{"id":2,"text":"C"},
					{"id":3,"text":"C++"},
					{"id":4,"text":"PHP"},
					{"id":5,"text":"English"}
					]

		var rank = 	[
					{"id":0,"text":"Noob"},
					{"id":1,"text":"Beginner"},
					{"id":2,"text":"Intermediate"},
					{"id":3,"text":"Advance"},
					{"id":4,"text":"Expert"},
					{"id":5,"text":"Legend"},
					{"id":6,"text":"Vinny"}
					]

		localStorage.setItem("skill",  JSON.stringify(skill));
		localStorage.setItem("rank",  JSON.stringify(rank));

		init();
		
		var counter = 1;
        $("#add-my-select").click(function(){
            var select2 = '<div class="select2" id="' + counter + '">' +
            '<select class="my-select-1"></select>\n' +
            '<select class="my-select-2"></select>\n' +
            '<button class="remove-my-select" onclick="remove(\'#' + counter + '\')"> - </button>\n' +
            '</div>'
            $(".select2-container").append(select2);
            init();
            counter++;
        });
	});

	function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getData);
    }

    var dict = {};

	function getData(){
		IN.API.Profile('me').fields(['first-name', 
			'last-name', 
			'email-address', 
			'public-profile-url', 
			'picture-urls::(original)']).result(displayData);
	}

	function displayData(profile){
		console.log(profile);
		var data = profile.values[0];

		name = data.firstName +" "+ data.lastName;
		email = data.emailAddress;
		linkedin = data.publicProfileUrl;
		picture = data.pictureUrls.values[0];

		$("#get-data").html(
			'<div class="profile">' +
      			'<div class="data">' +
      				'<img class="prof-picture" src="' + picture + '" alt="prof-pic" width="200" height="200"/>' +
      				'<h3>Personal Data</h3>' +
        			'<p class="prof-name"> Name : ' + name + '</p>' +
        			'<p class="prof-email"> Email : ' + email + '</p>' +
        			'<p class="prof-linkedin"> LinkedIn : ' + linkedin + '</p>' +
      			'</div>' +
    		'</div>'
    	); 

    	dict = data;
	}

	function updateData() { 

	    var skills = {};
        var types = $(".my-select-1 option:selected",".select2");
        var levels = $(".my-select-2 option:selected",".select2");
        var showScore = $('input[name="score"]:checked', "#show-score").val();

        for(i = 0; i < types.length; i++){
            skills[types[i].text] = levels[i].text;
        }
        console.log(skills);

    	$.ajax({
    		method : 'POST',
      		url : '{% url "lab-profile:update_data" %}',
      		dataType : 'json',
      		data : JSON.stringify({
                'skills': skills, 
                'showScore': showScore, 
                'name' : dict.firstName +" "+ dict.lastName,
        		'email': dict.emailAddress,
        		'linkedin': dict.publicProfileUrl,
        		'picture': dict.pictureUrls.values[0],
                }),

      		success : function(response) {
        		alert("Edit Complete!");
                document.location.reload("true");
      		},
      		error : function(error) {
        		console.log(error);
      		}
    	});
 	}

	var remove = function(id){
    	$("div").remove(id);
	};

	var init = function(){
		$('.my-select-1').select2({
				'data': JSON.parse(localStorage.getItem("skill"))
		})

		$('.my-select-2').select2({
				'data': JSON.parse(localStorage.getItem("rank"))
		})
	}
</script>